/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-28 03:39:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.MeyBank_005fUser.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Models.*;
import AppDBContext.*;
import java.util.*;
import Models.*;

public final class transaction2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/MeyBank_User/page/../../Layout/User_Index.jsp", Long.valueOf(1677477346171L));
    _jspx_dependants.put("/MeyBank_User/page/../../Layout/Checking_Login.jsp", Long.valueOf(1677049913234L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("AppDBContext");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("Models");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../assets/bootstrap.min.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css\" integrity=\"sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<!--     <link rel=\"stylesheet\" href=\"../MeyBank_User/css/account_index.css\"> -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css\" integrity=\"sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("    \r\n");
      out.write("  </head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    <!-- Hero section -->\r\n");
      out.write("	<section id=\"infinite2\" class=\"text-white tm-font-big tm-parallax\">\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-md tm-navbar2\" id=\"tmNav\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"tm-next\">\r\n");
      out.write("          <a href=\"index.jsp\" class=\"navbar-brand\"><img src=\"../../image/meybank-logo.png\" width=\"30px\">Meybank</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("          aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <i class=\"fas fa-bars navbar-toggler-icon\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("          <div class=\"navbar-nav ml-auto\">\r\n");
      out.write("            <a href=\"../../Logout\" class=\"logout-key\"><i class=\"fa-solid fa-unlock-keyhole\"></i>Logout</a>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write("  <section id=\"infinite2\" class=\"text-white\">\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"navbar tm-navbar2 navbar-select\">\r\n");
      out.write("      <div class=\"container-list\">\r\n");
      out.write("\r\n");
      out.write("        <div class=\"div-item\" id=\"box-0\">\r\n");
      out.write("        	<a href=\"index.jsp\" style=\"padding:10px 10px 0px 10px;\r\n");
      out.write("  					display:flex;\r\n");
      out.write("  					flex-direction: column;\r\n");
      out.write("  					transition: all .3s linear;\r\n");
      out.write("  					cursor: pointer;\r\n");
      out.write("  					color:white;\r\n");
      out.write("  					font-size:0.7rem\">\r\n");
      out.write("        		<i class=\"fa-solid fa-house\"></i>\r\n");
      out.write("            	<p>HOME</p>\r\n");
      out.write("        	</a> \r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"div-item\" id=\"box-1\" style=\"\r\n");
      out.write("        	display:flex;\r\n");
      out.write("    		flex-direction: column;\r\n");
      out.write("    		width: 170px;\r\n");
      out.write("    		transition: all .3s linear;\r\n");
      out.write("    		cursor: pointer;\r\n");
      out.write("    		border-right:1px solid #ced4da;\">\r\n");
      out.write("        <a href=\"account_index.jsp\" style=\"padding:10px 10px 0px 10px;\r\n");
      out.write("  					display:flex;\r\n");
      out.write("  					flex-direction: column;\r\n");
      out.write("  					transition: all .3s linear;\r\n");
      out.write("  					cursor: pointer;\r\n");
      out.write("  					color:white;\">\r\n");
      out.write("            <i class=\"fa-sharp fa-solid fa-file\"></i>\r\n");
      out.write("            <p>ACCOUNT</p>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"div-item\" id=\"box-2\" style=\"display:flex;\r\n");
      out.write("    		flex-direction: column;\r\n");
      out.write("    		width: 170px;\r\n");
      out.write("    		transition: all .3s linear;\r\n");
      out.write("    		cursor: pointer;\r\n");
      out.write("    		border-right:1px solid #ced4da;\">\r\n");
      out.write("        <a href=\"transaction_index.jsp\" style=\"padding:10px 10px 0px 10px;\r\n");
      out.write("  					display:flex;\r\n");
      out.write("  					flex-direction: column;\r\n");
      out.write("  					transition: all .3s linear;\r\n");
      out.write("  					cursor: pointer;\r\n");
      out.write("  					color:white;\">\r\n");
      out.write("            <i class=\"fa-solid fa-arrow-right-arrow-left\"></i>\r\n");
      out.write("            <p>FUND TRANSFER</p>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"div-item\" id=\"box-3\" style=\"display:flex;\r\n");
      out.write("    		flex-direction: column;\r\n");
      out.write("    		width: 170px;\r\n");
      out.write("    		transition: all .3s linear;\r\n");
      out.write("    		cursor: pointer;\r\n");
      out.write("    		border-right:1px solid #ced4da;\">\r\n");
      out.write("        <a href=\"payment_index.jsp\" style=\"padding:10px 10px 0px 10px;\r\n");
      out.write("  					display:flex;\r\n");
      out.write("  					flex-direction: column;\r\n");
      out.write("  					transition: all .3s linear;\r\n");
      out.write("  					cursor: pointer;\r\n");
      out.write("  					color:white;\">\r\n");
      out.write("            <i class=\"fa-solid fa-dollar-sign\"></i>\r\n");
      out.write("            <p>PAYMENT</p>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"div-item\" id=\"box-4\" style=\"display:flex;\r\n");
      out.write("    		flex-direction: column;\r\n");
      out.write("    		width: 170px;\r\n");
      out.write("    		transition: all .3s linear;\r\n");
      out.write("    		cursor: pointer;\r\n");
      out.write("    		border-right:1px solid #ced4da;\"> \r\n");
      out.write("        <a href=\"investment_index.jsp\" style=\"padding:10px 10px 0px 10px;\r\n");
      out.write("  					display:flex;\r\n");
      out.write("  					flex-direction: column;\r\n");
      out.write("  					transition: all .3s linear;\r\n");
      out.write("  					cursor: pointer;\r\n");
      out.write("  					color:white;\">\r\n");
      out.write("            <i class=\"fa-sharp fa-solid fa-arrow-trend-up\"></i>\r\n");
      out.write("            <p>INVESTMENT</p>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"div-item\" id=\"box-5\" style=\"display:flex;\r\n");
      out.write("    		flex-direction: column;\r\n");
      out.write("    		transition: all .3s linear;\r\n");
      out.write("    		cursor: pointer;\r\n");
      out.write("    		border-right:1px solid #ced4da;\">\r\n");
      out.write("        <a href=\"profile_index.jsp\" style=\"padding:10px 0px 0px 0px;\r\n");
      out.write("  					display:flex;\r\n");
      out.write("  					flex-direction: column;\r\n");
      out.write("  					transition: all .3s linear;\r\n");
      out.write("  					cursor: pointer;\r\n");
      out.write("  					color:white;\">\r\n");
      out.write("            <i class=\"fa-regular fa-user\"></i>\r\n");
      out.write("            <p>PROFILE MAINTENANCE</p>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"div-item\" id=\"box-6\" style=\"display:flex;\r\n");
      out.write("    		flex-direction: column;\r\n");
      out.write("    		width: 170px;\r\n");
      out.write("    		transition: all .3s linear;\r\n");
      out.write("    		cursor: pointer;\r\n");
      out.write("    		border-right:1px solid #ced4da;\">\r\n");
      out.write("        <a href=\"equity_index.jsp\" style=\"padding:10px 10px 0px 10px;\r\n");
      out.write("  					display:flex;\r\n");
      out.write("  					flex-direction: column;\r\n");
      out.write("  					transition: all .3s linear;\r\n");
      out.write("  					cursor: pointer;\r\n");
      out.write("  					color:white;\">\r\n");
      out.write("            <i class=\"fa-sharp fa-solid fa-layer-group\"></i>\r\n");
      out.write("            <p>EQUITY RESEARCH</p>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"div-item\" id=\"box-7\" style=\"display:flex;\r\n");
      out.write("    		flex-direction: column;\r\n");
      out.write("    		width: 170px;\r\n");
      out.write("    		transition: all .3s linear;\r\n");
      out.write("    		cursor: pointer;\r\n");
      out.write("    		border-right:1px solid #ced4da;\">\r\n");
      out.write("        <a href=\"mailbox_index.jsp\" style=\"padding:10px 10px 0px 10px;\r\n");
      out.write("  					display:flex;\r\n");
      out.write("  					flex-direction: column;\r\n");
      out.write("  					transition: all .3s linear;\r\n");
      out.write("  					cursor: pointer;\r\n");
      out.write("  					color:white;\">\r\n");
      out.write("            <i class=\"fa-solid fa-envelope\"></i>\r\n");
      out.write("            <p>MAILBOX</p>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"div-item\" id=\"box-8\" style=\"display:flex;\r\n");
      out.write("    		flex-direction: column;\r\n");
      out.write("    		width: 170px;\r\n");
      out.write("    		transition: all .3s linear;\r\n");
      out.write("    		cursor: pointer;\r\n");
      out.write("    		border-right:1px solid #ced4da;\">\r\n");
      out.write("        <a href=\"contact_index.jsp\" style=\"padding:10px 10px 0px 10px;\r\n");
      out.write("  					display:flex;\r\n");
      out.write("  					flex-direction: column;\r\n");
      out.write("  					transition: all .3s linear;\r\n");
      out.write("  					cursor: pointer;\r\n");
      out.write("  					color:white;\">\r\n");
      out.write("            <i class=\"fa-solid fa-phone\"></i>\r\n");
      out.write("            <p>CONTACT US</p>\r\n");
      out.write("            </a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</section>\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

		Account acc = (Account)session.getAttribute("Account");
 		User user = (User)session.getAttribute("User");
 		String time = (String)session.getAttribute("lastlogintime");
		if(acc == null || acc == null || time == null){
			response.sendRedirect("../../MeyBank_Home/page/home.jsp");
			return;
		}

      out.write('\r');
      out.write('\n');
 
Account account = (Account)session.getAttribute("Account");
api_Account api_acc = new api_Account();
api_User api_user = new api_User();
api_BankAccount api_bank = new api_BankAccount();
api_acc.getKEY(acc.getUsername(), acc.getPassword());
List<BankAccount> b_list = api_bank.getListBankAccount_By_AccountID(acc.getAccountID());
session.setAttribute("banklist", b_list);
List<BankAccount> bank_list = (List<BankAccount>)session.getAttribute("banklist");
Account Otheracc = (Account)session.getAttribute("OtherAccount");
BankAccount Otherbank = (BankAccount)session.getAttribute("OtherBankAccount");
BankAccount mybank = (BankAccount)session.getAttribute("tr1Bank");
User Otheruser = (User)session.getAttribute("OtherUser");
Transaction Othertr = (Transaction)session.getAttribute("tr1");
String amount = String.format("%.2f", Othertr.getAmount()).toString();
String sms = String.format("%.2f", Othertr.getSMSNotification()).toString();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/transaction1.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css'\r\n");
      out.write("	rel='stylesheet'>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	");

		String msg = (String)session.getAttribute("transaction1error");
		String otptime = (String)session.getAttribute("MBTROTHER");
		String MBTROTHEROTP = (String)session.getAttribute("MBTROTHEROTP");
		session.setAttribute("MBTROTHER", "");
		session.setAttribute("MBTROTHEROTP", "");
		if(msg == null){
			msg = "";
		}
		if(otptime == null){
			otptime = "";
		}
		if(MBTROTHEROTP == null){
			MBTROTHEROTP = "";
		}
	
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	<h1 id=\"otptime\" style=\"display:none;\">");
      out.print( MBTROTHEROTP );
      out.write("</h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<section class=\"context-nei\">\r\n");
      out.write("\r\n");
      out.write("		<div class=\"select-option\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"select-menu active\">\r\n");
      out.write("				<div class=\"select-btn\">\r\n");
      out.write("					<span class=\"sBtn-text\">MeyBank Account</span> <i\r\n");
      out.write("						class=\"bx bx-chevron-down\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("					<ul class=\"options\">\r\n");
      out.write("					<li><a class=\"option option-text\" href=\"transaction_own1.jsp\" id=\"transaction_own1\">To own MB</a></li>\r\n");
      out.write("					<li><a class=\"option option-text\" href=\"transaction1.jsp\" id=\"MB_transfer\">MB transfer</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"select-menu\">\r\n");
      out.write("				<div class=\"select-btn\">\r\n");
      out.write("					<span class=\"sBtn-text\">Other Bank Account</span> <i\r\n");
      out.write("						class=\"bx bx-chevron-down\"></i>\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("				<ul class=\"options\">\r\n");
      out.write("					<li><a class=\"option option-text\" href=\"transaction_IBG1.jsp\" id=\"IBG\">Interbank GIRO (IBG)</a></li>\r\n");
      out.write("				</ul>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<div class=\"input-box\">\r\n");
      out.write("\r\n");
      out.write("			<h1 class=\"input-box-title\">Other MeyBank Account</h1>\r\n");
      out.write("			<p class=\"input-box-title-p\">Transfer Other MeyBank Account\r\n");
      out.write("				(TOMA)</p>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container-xx\">\r\n");
      out.write("				<div class=\"steps-xx\">\r\n");
      out.write("					<span class=\"circlexx active\"></span> <span class=\"circlexx active\"></span>\r\n");
      out.write("					<span class=\"circlexx\"></span>\r\n");
      out.write("					<div class=\"progress-barxx\">\r\n");
      out.write("						<span class=\"indicatorxx\"></span>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<p id=\"error\"\r\n");
      out.write("				style=\"color: red; font-weight: bold; font-size: 0.9rem; padding: 10px 0px 0px 60px; text-align: center;\">");
      out.print( msg );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"container-table-box\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"item-bankchange2\">\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-child2\">\r\n");
      out.write("						<p class=\"fitst-p\">From Account</p>\r\n");
      out.write("						<p class=\"fitst-p2\">");
      out.print( mybank.getBankAccNo() );
      out.write('(');
      out.print( mybank.getAccountType());
      out.write(")</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-child2\">\r\n");
      out.write("						<p class=\"fitst-p\">Beneficiary Bank</p>\r\n");
      out.write("						<p class=\"fitst-p2\">");
      out.print( Otheracc.getBankType() );
      out.write("</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-child2\">\r\n");
      out.write("						<p class=\"fitst-p\">Beneficiary Account No</p>\r\n");
      out.write("						<p class=\"fitst-p2\">");
      out.print( Othertr.getCredit() );
      out.write("</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-child2\">\r\n");
      out.write("						<p class=\"fitst-p\">Beneficiary Name</p>\r\n");
      out.write("						<p class=\"fitst-p2\">");
      out.print( Otherbank.getAccountType() );
      out.write("</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-child2\">\r\n");
      out.write("						<p class=\"fitst-p\">Other Payment Detail</p>\r\n");
      out.write("						<p class=\"fitst-p2\">");
      out.print( Othertr.getOtherDescription() );
      out.write("</p>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("					<div class=\"item-child2\">\r\n");
      out.write("						<p class=\"fitst-p\">Recipient Reference</p>\r\n");
      out.write("						<p class=\"fitst-p2\">");
      out.print( Othertr.getDescription() );
      out.write("</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"item-child2\">\r\n");
      out.write("						<p class=\"fitst-p\">Transaction Amount</p>\r\n");
      out.write("						<p class=\"fitst-p2\">\r\n");
      out.write("							RM\r\n");
      out.write("							");
      out.print( amount );
      out.write("</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"item-child2\">\r\n");
      out.write("						<p class=\"fitst-p\">Instant Transfer Service Change</p>\r\n");
      out.write("						<p class=\"fitst-p2\">\r\n");
      out.write("							RM\r\n");
      out.write("							");
      out.print( sms );
      out.write("</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					\r\n");
      out.write("					<div class=\"item-child2\">\r\n");
      out.write("						<p class=\"fitst-p\">PAC</p>\r\n");
      out.write("						<div>\r\n");
      out.write("							<input type=\"text\" class=\"form-control form-control-input\"\r\n");
      out.write("								id=\"otp12\" name=\"otp12\" onkeyup=\"value=value.replace(/\\D/g,'')\" onafterpaste=\"value=value.replace(/\\D/g,'')\">\r\n");
      out.write("							<p id=\"otptext\" style=\"display:none;\">there is still time <span id=\"time1\" style=\"color:red;\">120</span><span style=\"color:red;\"> s</span></p>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("				<section class=\"section-box-acc\">\r\n");
      out.write("\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"btn-hr\">\r\n");
      out.write("                	<a href=\"transaction_index.jsp\" class=\"btn btn-danger\">Cancel</a>\r\n");
      out.write("                	<a href=\"../../Tr_OTP?Action=MBTR\" class=\"btn btn-danger\">Request PAC Now</a>\r\n");
      out.write("                	<a href=\"../../PayMentTR?Action=MBTR\" class=\"btn btn-danger\" id=\"btnn\" style=\"visibility: hidden;\">Confirm</a>\r\n");
      out.write("            	</div>\r\n");
      out.write("			</section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</section>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("	<script src=\"../script/transaction1.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("	\r\n");
      out.write("	if($(\"#otptime\").html() != \"\"){\r\n");
      out.write("	 	daojishi();\r\n");
      out.write("	 	$(\"#otptext\").css(\"display\",\"block\");\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	 function daojishi(){\r\n");
      out.write("         var starttime = document.getElementById(\"time1\").innerHTML;\r\n");
      out.write("         if(starttime == 0){\r\n");
      out.write("         	window.location.href=\"../../MeyBank_Home/page/home.jsp\";\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("         setTimeout(\"daojishi()\",1000);\r\n");
      out.write("         starttime--;\r\n");
      out.write("         document.getElementById(\"time1\").innerHTML = starttime;\r\n");
      out.write("     }\r\n");
      out.write("	\r\n");
      out.write("  	$(function(){\r\n");
      out.write("  		\r\n");
      out.write("  		$(\"#box-2\").css(\"background\",\"red\");\r\n");
      out.write("  		$(\"#MB_transfer\").css(\"background\",\"red\");\r\n");
      out.write("  		\r\n");
      out.write("  		$(\"#otp12\").keyup(function(){\r\n");
      out.write("  			var value = $(this).val();\r\n");
      out.write("  			var otp = $(\"#otptime\").html();\r\n");
      out.write("  			if(value == otp){\r\n");
      out.write("  				$(\"#btnn\").css(\"visibility\",\"visible\");\r\n");
      out.write("  			}else{\r\n");
      out.write("  				$(\"#btnn\").css(\"visibility\",\"hidden\");\r\n");
      out.write("  			}\r\n");
      out.write("  		})\r\n");
      out.write("  		\r\n");
      out.write("  	})\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
