/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-03-01 01:42:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.MeyBank_005fUser.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Models.*;
import java.util.*;
import Models.*;

public final class User_005fTransaction_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/MeyBank_User/page/../../Layout/Checking_Login.jsp", Long.valueOf(1677049913234L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("Models");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

		Account acc = (Account)session.getAttribute("Account");
 		User user = (User)session.getAttribute("User");
 		String time = (String)session.getAttribute("lastlogintime");
		if(acc == null || acc == null || time == null){
			response.sendRedirect("../../MeyBank_Home/page/home.jsp");
			return;
		}

      out.write("\r\n");
      out.write("\r\n");

User u = (User) session.getAttribute("User");
String amountUser = (String) session.getAttribute("amountUser");
String senUser = (String) session.getAttribute("senUser");
String countUser = (String) session.getAttribute("countUser");
String amountUsers = (String) session.getAttribute("amountUsers");
String senUsers = (String) session.getAttribute("senUsers");
String countUsers = (String) session.getAttribute("countUsers");
List<User> listUser = (List<User>) session.getAttribute("TodayUser");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Document</title>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css\"\r\n");
      out.write("	integrity=\"sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T\"\r\n");
      out.write("	crossorigin=\"anonymous\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/user.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link href='https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css'\r\n");
      out.write("	rel='stylesheet'>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"app-container\">\r\n");
      out.write("		<div class=\"app-left\">\r\n");
      out.write("			<button class=\"close-menu\">\r\n");
      out.write("				<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\"\r\n");
      out.write("					viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("					stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("					class=\"feather feather-x\">\r\n");
      out.write("					<line x1=\"18\" y1=\"6\" x2=\"6\" y2=\"18\" />\r\n");
      out.write("					<line x1=\"6\" y1=\"6\" x2=\"18\" y2=\"18\" /></svg>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"app-logo\">\r\n");
      out.write("				<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\"\r\n");
      out.write("					viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("					stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("					class=\"feather feather-bar-chart-2\">\r\n");
      out.write("              <line x1=\"18\" y1=\"20\" x2=\"18\" y2=\"10\" />\r\n");
      out.write("              <line x1=\"12\" y1=\"20\" x2=\"12\" y2=\"4\" />\r\n");
      out.write("              <line x1=\"6\" y1=\"20\" x2=\"6\" y2=\"14\" />       </svg>\r\n");
      out.write("				<span>MeyBank Profile</span>\r\n");
      out.write("			</div>\r\n");
      out.write("			<ul class=\"nav-list\">\r\n");
      out.write("				<li class=\"nav-list-item\"><a class=\"nav-list-link\"\r\n");
      out.write("					href=\"User_Home.jsp\"> <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\"\r\n");
      out.write("							height=\"24\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("							stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("							class=\"feather feather-columns\">\r\n");
      out.write("							<path\r\n");
      out.write("								d=\"M12 3h7a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-7m0-18H5a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h7m0-18v18\" /></svg>\r\n");
      out.write("						Information\r\n");
      out.write("				</a></li>\r\n");
      out.write("				<li class=\"nav-list-item active\"><a class=\"nav-list-link\" href=\"User_Transaction.jsp\">\r\n");
      out.write("						<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\"\r\n");
      out.write("							viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("							stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("							class=\"feather feather-briefcase\">\r\n");
      out.write("							<rect x=\"2\" y=\"7\" width=\"20\" height=\"14\" rx=\"2\" ry=\"2\" />\r\n");
      out.write("							<path d=\"M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16\" /></svg>\r\n");
      out.write("						Transaction History\r\n");
      out.write("				</a></li>\r\n");
      out.write("\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"app-main2\">\r\n");
      out.write("			\r\n");
      out.write("			   <h1>Transaction History Select Type</h1>\r\n");
      out.write("            <div class=\"options\">\r\n");
      out.write("                <div class=\"optionhoo active\" style=\"--optionBackground:url(https://66.media.tumblr.com/6fb397d822f4f9f4596dff2085b18f2e/tumblr_nzsvb4p6xS1qho82wo1_1280.jpg);\">\r\n");
      out.write("                   <div class=\"shadow\"></div>\r\n");
      out.write("                   <div class=\"label\">\r\n");
      out.write("                      <div class=\"icon\">\r\n");
      out.write("                         <i class=\"fas fa-walking\"></i>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                         <div class=\"main\">All History</div>\r\n");
      out.write("                         <a href=\"../../History?Action=All\" class=\"sub\">Go to interface</a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"optionhoo\" style=\"--optionBackground:url(https://66.media.tumblr.com/8b69cdde47aa952e4176b4200052abf4/tumblr_o51p7mFFF21qho82wo1_1280.jpg);\">\r\n");
      out.write("                   <div class=\"shadow\"></div>\r\n");
      out.write("                   <div class=\"label\">\r\n");
      out.write("                      <div class=\"icon\">\r\n");
      out.write("                         <i class=\"fas fa-snowflake\"></i>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                         <div class=\"main\">Own History</div>\r\n");
      out.write("                         <a href=\"../../History?Action=Own\" class=\"sub\">Go to interface</a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"optionhoo\" style=\"--optionBackground:url(https://66.media.tumblr.com/5af3f8303456e376ceda1517553ba786/tumblr_o4986gakjh1qho82wo1_1280.jpg);\">\r\n");
      out.write("                   <div class=\"shadow\"></div>\r\n");
      out.write("                   <div class=\"label\">\r\n");
      out.write("                      <div class=\"icon\">\r\n");
      out.write("                         <i class=\"fas fa-tree\"></i>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                         <div class=\"main\">Other MB History</div>\r\n");
      out.write("                         <a href=\"../../History?Action=Other\" class=\"sub\">Go to interface</a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"optionhoo\" style=\"--optionBackground:url(https://66.media.tumblr.com/5516a22e0cdacaa85311ec3f8fd1e9ef/tumblr_o45jwvdsL11qho82wo1_1280.jpg);\">\r\n");
      out.write("                   <div class=\"shadow\"></div>\r\n");
      out.write("                   <div class=\"label\">\r\n");
      out.write("                      <div class=\"icon\">\r\n");
      out.write("                         <i class=\"fas fa-tint\"></i>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                         <div class=\"main\">IBG History</div>\r\n");
      out.write("                         <a href=\"../../History?Action=IBG\" class=\"sub\">Go to interface</a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"optionhoo\" style=\"--optionBackground:url(https://66.media.tumblr.com/f19901f50b79604839ca761cd6d74748/tumblr_o65rohhkQL1qho82wo1_1280.jpg);\">\r\n");
      out.write("                   <div class=\"shadow\"></div>\r\n");
      out.write("                   <div class=\"label\">\r\n");
      out.write("                      <div class=\"icon\">\r\n");
      out.write("                         <i class=\"fas fa-sun\"></i>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div class=\"info\">\r\n");
      out.write("                         <div class=\"main\">Payment History</div>\r\n");
      out.write("                         <a href=\"../../History?Action=Payment\" class=\"sub\">Go to interface</a>\r\n");
      out.write("                      </div>\r\n");
      out.write("                   </div>\r\n");
      out.write("                </div>\r\n");
      out.write("             </div>\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		<div class=\"app-right\">\r\n");
      out.write("			<button class=\"close-right\">\r\n");
      out.write("				<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"24\" height=\"24\"\r\n");
      out.write("					viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("					stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("					class=\"feather feather-x\">\r\n");
      out.write("					<line x1=\"18\" y1=\"6\" x2=\"6\" y2=\"18\" />\r\n");
      out.write("					<line x1=\"6\" y1=\"6\" x2=\"18\" y2=\"18\" /></svg>\r\n");
      out.write("			</button>\r\n");
      out.write("			<div class=\"profile-box\">\r\n");
      out.write("				<div class=\"profile-photo-wrapper\">\r\n");
      out.write("					<img src=\"../../image/User/");
      out.print(u.getIMG());
      out.write("\" alt=\"profile\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<p class=\"profile-text\">");
      out.print(u.getFullName());
      out.write("</p>\r\n");
      out.write("				<p class=\"profile-subtext\">");
      out.print(u.getEmail());
      out.write("</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"app-right-section\">\r\n");
      out.write("				<div class=\"app-right-section-header\">\r\n");
      out.write("					<h2>Activity</h2>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"activity-line\">\r\n");
      out.write("					<span class=\"activity-icon warning\"> <svg\r\n");
      out.write("							xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"\r\n");
      out.write("							viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("							stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("							class=\"feather feather-alert-circle\">\r\n");
      out.write("							<circle cx=\"12\" cy=\"12\" r=\"10\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\" /></svg>\r\n");
      out.write("					</span>\r\n");
      out.write("					<div class=\"activity-text-wrapper\">\r\n");
      out.write("						<p class=\"activity-text\">HOME</p>\r\n");
      out.write("						<a class=\"activity-link\" href=\"index.jsp\">Go Immediately</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"activity-line\">\r\n");
      out.write("					<span class=\"activity-icon applicant\"> <svg\r\n");
      out.write("							xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"\r\n");
      out.write("							viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("							stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("							class=\"feather feather-alert-circle\">\r\n");
      out.write("							<circle cx=\"12\" cy=\"12\" r=\"10\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\" /></svg>\r\n");
      out.write("					</span>\r\n");
      out.write("					<div class=\"activity-text-wrapper\">\r\n");
      out.write("						<p class=\"activity-text\">ACCOUNT</p>\r\n");
      out.write("						<a class=\"activity-link\" href=\"account_index.jsp\">Go Immediately</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"activity-line\">\r\n");
      out.write("					<span class=\"activity-icon close\"> <svg\r\n");
      out.write("							xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"\r\n");
      out.write("							viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("							stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("							class=\"feather feather-alert-circle\">\r\n");
      out.write("							<circle cx=\"12\" cy=\"12\" r=\"10\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\" /></svg>\r\n");
      out.write("					</span>\r\n");
      out.write("					<div class=\"activity-text-wrapper\">\r\n");
      out.write("						<p class=\"activity-text\">FUND TRANSFER</p>\r\n");
      out.write("						<a class=\"activity-link\" href=\"transaction_index.jsp\">Go Immediately</a>\r\n");
      out.write("					</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"activity-line\">\r\n");
      out.write("					<span class=\"activity-icon draft\"> <svg\r\n");
      out.write("							xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"\r\n");
      out.write("							viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("							stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("							class=\"feather feather-alert-circle\">\r\n");
      out.write("							<circle cx=\"12\" cy=\"12\" r=\"10\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\" /></svg>\r\n");
      out.write("					</span>\r\n");
      out.write("					<div class=\"activity-text-wrapper\">\r\n");
      out.write("						<p class=\"activity-text\">PAYMENT</p>\r\n");
      out.write("						<a class=\"activity-link\" href=\"payment_index.jsp\">Go Immediately</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"activity-line\">\r\n");
      out.write("					<span class=\"activity-icon warning\"> <svg\r\n");
      out.write("							xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"\r\n");
      out.write("							viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("							stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("							class=\"feather feather-alert-circle\">\r\n");
      out.write("							<circle cx=\"12\" cy=\"12\" r=\"10\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\" /></svg>\r\n");
      out.write("					</span>\r\n");
      out.write("					<div class=\"activity-text-wrapper\">\r\n");
      out.write("						<p class=\"activity-text\">INVESTMENT</p>\r\n");
      out.write("						<a class=\"activity-link\" href=\"investment_index.jsp\">Go Immediately</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"activity-line\">\r\n");
      out.write("					<span class=\"activity-icon applicant\"> <svg\r\n");
      out.write("							xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"\r\n");
      out.write("							viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("							stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("							class=\"feather feather-alert-circle\">\r\n");
      out.write("							<circle cx=\"12\" cy=\"12\" r=\"10\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\" /></svg>\r\n");
      out.write("					</span>\r\n");
      out.write("					<div class=\"activity-text-wrapper\">\r\n");
      out.write("						<p class=\"activity-text\">EQUITY RESEARCH</p>\r\n");
      out.write("						<a class=\"activity-link\" href=\"equity_index.jsp\">Go Immediately</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				<div class=\"activity-line\">\r\n");
      out.write("					<span class=\"activity-icon close\"> <svg\r\n");
      out.write("							xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"\r\n");
      out.write("							viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\"\r\n");
      out.write("							stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"\r\n");
      out.write("							class=\"feather feather-alert-circle\">\r\n");
      out.write("							<circle cx=\"12\" cy=\"12\" r=\"10\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\" />\r\n");
      out.write("							<line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\" /></svg>\r\n");
      out.write("					</span>\r\n");
      out.write("					<div class=\"activity-text-wrapper\">\r\n");
      out.write("						<p class=\"activity-text\">CONTACT US</p>\r\n");
      out.write("						<a class=\"activity-link\" href=\"contact_index.jsp\">Go Immediately</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("	<script src=\"../script/user.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
