/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-22 03:00:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.MeyBank_005fHome.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <!-- Basic -->\r\n");
      out.write("  <meta charset=\"utf-8\" />\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\r\n");
      out.write("  <!-- Mobile Metas -->\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\r\n");
      out.write("  <!-- Site Metas -->\r\n");
      out.write("  <link rel=\"icon\" href=\"images/favicon.png\" type=\"image/gif\" />\r\n");
      out.write("  <title> Cafeesa| PRAROZ </title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../../assets/bootstrap.min.css\" />\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"../css/contact.css\" />\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("  <section id=\"infinite2\" class=\"text-white tm-font-big tm-parallax\">\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-md tm-navbar2\" id=\"tmNav\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"tm-next\">\r\n");
      out.write("          <a href=\"home.jsp\" class=\"navbar-brand\"><img src=\"../../image/meybank-logo.png\" width=\"30px\">Meybank</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("          aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <i class=\"fas fa-bars navbar-toggler-icon\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("          <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link tm-nav-link\" href=\"home.jsp\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link tm-nav-link\" href=\"whatwedo.jsp\">What We Do</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link tm-nav-link\" href=\"policy.jsp\">Policy</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link tm-nav-link\" href=\"faqs.jsp\">FAQ's</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\" style=\"background-color: rgb(153, 51, 80);border-radius: 5px;color: #FFF;\">\r\n");
      out.write("              <a class=\"nav-link tm-nav-link\" href=\"contact.jsp\">Contact</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- contact section -->\r\n");
      out.write("<section class=\"contact_section layout_padding\">\r\n");
      out.write("  <div class=\"contact_bg_box\">\r\n");
      out.write("    <img src=\"https://images6.alphacoders.com/485/485875.jpg\" alt=\"\">\r\n");
      out.write("  </div>\r\n");
      out.write("  <div class=\"container\">\r\n");
      out.write("    <div class=\"heading_container heading_center\">\r\n");
      out.write("      <h2>CONTACT</h2>\r\n");
      out.write("    </div> \r\n");
      out.write("    <div class=\"\">\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("        <div class=\"col-md-9 mx-auto\">\r\n");
      out.write("          <form action=\"../../contact\" method=\"post\">\r\n");
      out.write("            <div class=\"contact_form-container\">\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                  <input type=\"text\" placeholder=\"Full Name\" name=\"fullname\" id=\"fullname\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                  <input type=\"email\" placeholder=\"Email\" name=\"email\" id=\"email\">\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"row\">\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                  <input type=\"text\" placeholder=\"Phone Number\" name=\"phone\" id=\"phone\" onkeyup=\"value=value.replace(/\\D/g,'')\" onafterpaste=\"value=value.replace(/\\D/g,'')\" maxlength=\"10\"/>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-sm-6\">\r\n");
      out.write("                  <input type=\"text\" placeholder=\"Number of NRIC\" name=\"nric\" id=\"nric\" onkeyup=\"value=value.replace(/\\D/g,'')\" onafterpaste=\"value=value.replace(/\\D/g,'')\" maxlength=\"12\"/>\r\n");
      out.write("                </div> \r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"\">\r\n");
      out.write("                <input type=\"text\" placeholder=\"Additional Note\" class=\"message_input\" name=\"text\" id=\"text\"/>\r\n");
      out.write("              </div>\r\n");
      out.write("              <div class=\"btn_box\">\r\n");
      out.write("                <button type=\"submit\" id=\"btnn\" disabled>Send</button>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</section>\r\n");
      out.write("<!-- End of contact section -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("var fullname = false;\r\n");
      out.write("var email = false;\r\n");
      out.write("var phone = false;\r\n");
      out.write("var nric = false;\r\n");
      out.write("var text = false;\r\n");
      out.write("\r\n");
      out.write("$(\"#fullname\").keyup(function(){\r\n");
      out.write("	if($(this).val() != \"\"){\r\n");
      out.write("		fullname = true;\r\n");
      out.write("	}else{\r\n");
      out.write("		fullname = false;\r\n");
      out.write("	}\r\n");
      out.write("	CheckOPen(fullname,email,phone,nric,text);\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("$(\"#email\").keyup(function(){\r\n");
      out.write("	if($(this).val() != \"\" && $(this).val().includes(\"@gmail.com\")){\r\n");
      out.write("		email = true;\r\n");
      out.write("	}else{\r\n");
      out.write("		email = false;\r\n");
      out.write("	}\r\n");
      out.write("	CheckOPen(fullname,email,phone,nric,text);\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("$(\"#phone\").keyup(function(){\r\n");
      out.write("	if($(this).val() != \"\" && $(this).val().length == 10){\r\n");
      out.write("		phone = true;\r\n");
      out.write("	}else{\r\n");
      out.write("		phone = false;\r\n");
      out.write("	}\r\n");
      out.write("	CheckOPen(fullname,email,phone,nric,text);\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("$(\"#nric\").keyup(function(){\r\n");
      out.write("	if($(this).val() != \"\" && $(this).val().length == 12){\r\n");
      out.write("		nric = true;\r\n");
      out.write("	}else{\r\n");
      out.write("		nric = false;\r\n");
      out.write("	}\r\n");
      out.write("	CheckOPen(fullname,email,phone,nric,text);\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("$(\"#text\").keyup(function(){\r\n");
      out.write("	if($(this).val() != \"\"){\r\n");
      out.write("		text = true;\r\n");
      out.write("	}else{\r\n");
      out.write("		text = false;\r\n");
      out.write("	}\r\n");
      out.write("	CheckOPen(fullname,email,phone,nric,text);\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function CheckOPen(fullname,email,phone,nric,text){\r\n");
      out.write("	console.log(\"1  \" +fullname)\r\n");
      out.write("	console.log(\"2  \" +email)\r\n");
      out.write("	console.log(\"3  \" +phone)\r\n");
      out.write("	console.log(\"4  \" +nric)\r\n");
      out.write("	console.log(\"5  \" +text)\r\n");
      out.write("	if(fullname == true && email == true && phone == true && nric == true && text == true){\r\n");
      out.write("		$(\"#btnn\").prop(\"disabled\",false);\r\n");
      out.write("	}else{\r\n");
      out.write("		$(\"#btnn\").prop(\"disabled\",true);\r\n");
      out.write("	}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
