/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-21 10:20:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.MeyBank_005fHome.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class policy_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Document</title>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../assets/bootstrap.min.css\" />\r\n");
      out.write("  	<link rel=\"stylesheet\" href=\"../css/style.css\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css\" integrity=\"sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==\" crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("     <!-- Hero section -->\r\n");
      out.write("  <section id=\"infinite2\" class=\"text-white tm-font-big tm-parallax\">\r\n");
      out.write("    <!-- Navigation -->\r\n");
      out.write("    <nav class=\"navbar navbar-expand-md tm-navbar2\" id=\"tmNav\">\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <div class=\"tm-next\">\r\n");
      out.write("          <a href=\"home.jsp\" class=\"navbar-brand\"><img src=\"../../image/meybank-logo.png\" width=\"30px\">Meybank</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarSupportedContent\"\r\n");
      out.write("          aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("          <i class=\"fas fa-bars navbar-toggler-icon\"></i>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("          <ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link tm-nav-link\" href=\"home.jsp\">Home</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link tm-nav-link\" href=\"whatwedo.jsp\">What We Do</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\" style=\"background-color: rgb(153, 51, 80);border-radius: 5px;color: #FFF;\">\r\n");
      out.write("              <a class=\"nav-link tm-nav-link\" href=\"policy.jsp\">Policy</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link tm-nav-link\" href=\"faqs.jsp\">FAQ's</a>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"nav-item\">\r\n");
      out.write("              <a class=\"nav-link tm-nav-link\" href=\"contact.jsp\">Contact</a>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("  </section>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"img-policy\">\r\n");
      out.write("        <img src=\"https://monday.com/blog/wp-content/uploads/2022/09/pasted-image-0-16.jpg\"\r\n");
      out.write("            class=\"d-block\" alt=\"...\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Services-->\r\n");
      out.write("    <section class=\"container py-5 my-md-2 my-lg-3 my-xl-4 my-xxl-5\">\r\n");
      out.write("        <div class=\"row align-items-center py-1 py-sm-3 py-md-4 my-lg-2\" id=\"services\">\r\n");
      out.write("            <div class=\"col-lg-4 offset-xl-1\">\r\n");
      out.write("                <h2 class=\"h1 text-center text-lg-start pb-3 pb-lg-1\">Security <span style=\"color:red;\">Policy</span></h2>\r\n");
      out.write("                <!-- Show on screens > 992px-->\r\n");
      out.write("                <ul class=\"list-unstyled d-none d-lg-block pb-3 mb-3 mb-lg-4\">\r\n");
      out.write("                    <li class=\"d-flex pt-2\"><i class=\"bi bi-check-lg me-2\"></i></i> Username and Password</li>\r\n");
      out.write("                    <li class=\"d-flex pt-2\"><i class=\"bi bi-check-lg me-2\"></i></i> Information Protection</li>\r\n");
      out.write("                    <li class=\"d-flex pt-2\"><i class=\"bi bi-check-lg me-2\"></i></i> Data Confidentiality and Data Integrity</li>\r\n");
      out.write("                    <li class=\"d-flex pt-2\"><i class=\"bi bi-check-lg me-2\"></i></i> Systems security and monitoring</li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-lg-8 col-xl-7 col-xxl-6\">\r\n");
      out.write("                <div class=\"row row-cols-1 row-cols-sm-2\">\r\n");
      out.write("                    <div class=\"col\">\r\n");
      out.write("                        <div class=\"card border-0 bg-faded-primary\">\r\n");
      out.write("                            <div class=\"card-body body1\"><i class=\"bi  bash bi-gear-wide-connected\"></i>\r\n");
      out.write("                                <h3 class=\"h4\">Protect Yourself and Your Information Online</h3>\r\n");
      out.write("                                <p class=\"fs-sm\">Be careful when you do your banking online. There have been cases of copycat web sites created by unauthorised persons posing as authentic web sites.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card border-0 bg-faded-info mt-4\">\r\n");
      out.write("                            <div class=\"card-body body2\"><i class=\"bi  bash  bi-envelope\"></i>\r\n");
      out.write("                                <h3 class=\"h4\">Information Protection</h3>\r\n");
      out.write("                                <p class=\"fs-sm\">Do not send any information about your account via e-mail.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col pt-lg-3\">\r\n");
      out.write("                        <div class=\"card border-0 bg-faded-warning mt-4 mt-sm-0 mt-lg-4\">\r\n");
      out.write("                            <div class=\"card-body body3\"><i class=\"bi  bash bi-lightbulb-fill\"></i>\r\n");
      out.write("                                <h3 class=\"h4\">Updating your browser</h3>\r\n");
      out.write("                                <p class=\"fs-sm\">Always update your browser when new versions are released because they often include new security features.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"card border-0 bg-faded-danger mt-4\">\r\n");
      out.write("                            <div class=\"card-body body4\"><i class=\"bi  bash bi-telegram\"></i>\r\n");
      out.write("                                <h3 class=\"h4\">Security Tips</h3>\r\n");
      out.write("                                <p class=\"fs-sm\">Always log out of MeyBank.com immediately after completing transactions and before visiting other websites.</p>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <!-- Show button on screens < 992px-->\r\n");
      out.write("                <div class=\"d-lg-none text-center pt-3 mt-3 mt-sm-4\"><a class=\"btn btn-primary\" href=\"#\">See all\r\n");
      out.write("                        servises</a></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("    <!-- Tools-->\r\n");
      out.write("    <section class=\"container containerparticular\" id=\"tools\">\r\n");
      out.write("        <div class=\"bg-faded-primary rounded-5 py-5 px-4 p-sm-5\">\r\n");
      out.write("            <div class=\"d-lg-flex align-items-center g-0 py-2 py-sm-3 py-md-4 p-xl-5\">\r\n");
      out.write("                <div class=\"order-lg-2 text-center text-lg-start ps-lg-5 mx-auto me-lg-0\">\r\n");
      out.write("                    <h2 class=\"h1 mb-4\">The <span style=\"color:red;\">tools</span> <br class='d-none d-lg-inline'>we work with</h2>\r\n");
      out.write("                    <p class=\"pb-3 mb-3 mb-lg-4\">Morbi et massa fames ac scelerisque sit commodo dignissim faucibus vel\r\n");
      out.write("                        quisque proin lectus. Morbi et massa fames ac scelerisque sit commodo dignissim.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <div class=\"order-lg-1 w-100 mx-auto mx-lg-0\" style=\"max-width: 558px;\">\r\n");
      out.write("                    <div class=\"row row-cols-3 g-3 g-sm-4 g-lg-3 g-xl-4 column-box\" style=\"margin-right:10px;\">\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <div class=\"bg-light rounded-3 box-img\" data-aos=\"zoom-in\" data-aos-easing=\"ease-out-back\"\r\n");
      out.write("                                data-aos-delay=\"300\"><img class=\"box-img-img\" src=\"../../image/bing.svg\" class=\"img-assets\" alt=\"Bing\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <div class=\"bg-light rounded-3 box-img\" data-aos=\"zoom-in\" data-aos-easing=\"ease-out-back\"\r\n");
      out.write("                                data-aos-delay=\"500\"><img class=\"box-img-img\" src=\"../../image/facebook.svg\" alt=\"Facebook\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <div class=\"bg-light rounded-3 box-img\" data-aos=\"zoom-in\" data-aos-easing=\"ease-out-back\"\r\n");
      out.write("                                data-aos-delay=\"200\"><img class=\"d-dark-mode-none box-img-img\" src=\"../../image/microsoft-dark.svg\"\r\n");
      out.write("                                    alt=\"Facebook\"><img class=\"d-none d-dark-mode-block box-img-img\"\r\n");
      out.write("                                    src=\"../../image/microsoft-light.svg\" alt=\"Facebook\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <div class=\"bg-light rounded-3 box-img\" data-aos=\"zoom-in\" data-aos-easing=\"ease-out-back\"\r\n");
      out.write("                                data-aos-delay=\"800\"><img class=\"box-img-img\" src=\"../../image/google.svg\" alt=\"Google\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <div class=\"bg-light rounded-3 box-img\" data-aos=\"zoom-in\" data-aos-easing=\"ease-out-back\"><img\r\n");
      out.write("                                    class=\"d-dark-mode-none box-img-img\" src=\"../../image/google-ads-dark.svg\" alt=\"Google Ads\"><img\r\n");
      out.write("                                    class=\"d-none d-dark-mode-block box-img-img\" src=\"../../image/google-ads-light.svg\"\r\n");
      out.write("                                    alt=\"Google Ads\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <div class=\"bg-light rounded-3 box-img\" data-aos=\"zoom-in\" data-aos-easing=\"ease-out-back\"\r\n");
      out.write("                                data-aos-delay=\"600\"><img class=\"d-dark-mode-none box-img-img\" src=\"../../image/admitad-dark.svg\"\r\n");
      out.write("                                    alt=\"Admitad\"><img class=\"d-none d-dark-mode-block box-img-img\"\r\n");
      out.write("                                    src=\"../../image/admitad-light.svg\" alt=\"Admitad\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <div class=\"bg-light rounded-3 box-img\" data-aos=\"zoom-in\" data-aos-easing=\"ease-out-back\"\r\n");
      out.write("                                data-aos-delay=\"400\"><img class=\"d-dark-mode-none box-img-img\"\r\n");
      out.write("                                    src=\"../../image/google-analytics-dark.svg\" alt=\"Google Analytics\"><img\r\n");
      out.write("                                    class=\"d-none d-dark-mode-block box-img-img\" src=\"../../image/google-analytics-light.svg\"\r\n");
      out.write("                                    alt=\"Google Analytics\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <div class=\"bg-light rounded-3 box-img\" data-aos=\"zoom-in\" data-aos-easing=\"ease-out-back\"\r\n");
      out.write("                                data-aos-delay=\"700\"><img class=\"d-dark-mode-none box-img-img\" src=\"../../image/instagram-dark.svg\"\r\n");
      out.write("                                    alt=\"Instagram\"><img class=\"d-none d-dark-mode-block box-img-img\"\r\n");
      out.write("                                    src=\"../../image/instagram-light.svg\" alt=\"Instagram\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col\">\r\n");
      out.write("                            <div class=\"bg-light rounded-3 box-img\" data-aos=\"zoom-in\" data-aos-easing=\"ease-out-back\"\r\n");
      out.write("                                data-aos-delay=\"100\"><img class=\"d-dark-mode-none box-img-img\" src=\"../../image/tiktok-dark.svg\"\r\n");
      out.write("                                    alt=\"TikTok\"><img class=\"d-none d-dark-mode-block box-img-img\" src=\"../../image/tiktok-light.svg\"\r\n");
      out.write("                                    alt=\"TikTok\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
