/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-20 15:36:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.MeyBank_005fSignUp.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class page2_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
 
	String page1 = (String)session.getAttribute("page1");
	if(page1 == null){
		response.sendRedirect("page1.jsp");
		return;
	}

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("  <head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\r\n");
      out.write("    <script\r\n");
      out.write("      src=\"https://kit.fontawesome.com/64d58efce2.js\"\r\n");
      out.write("      crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../css/style.css\" />\r\n");
      out.write("    <title>Sign in & Sign up Form</title>\r\n");
      out.write("  </head>\r\n");
      out.write("  <body>\r\n");
      out.write("  \r\n");
      out.write("  ");

		String msg = (String)session.getAttribute("errorpage2");
		if(msg == null){
			msg = "";
		}
	
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <div class=\"container sign-up-mode\">\r\n");
      out.write("      <div class=\"forms-container\">\r\n");
      out.write("        <div class=\"signin-signup\">\r\n");
      out.write("\r\n");
      out.write("          <div class=\"container-xx\">\r\n");
      out.write("            <div class=\"steps-xx\">\r\n");
      out.write("              <span class=\"circlexx active\">1</span>\r\n");
      out.write("              <span class=\"circlexx active\">2</span>\r\n");
      out.write("              <span class=\"circlexx\">3</span>\r\n");
      out.write("              <span class=\"circlexx\">4</span>\r\n");
      out.write("              <div class=\"progress-barxx\">\r\n");
      out.write("                <span class=\"indicatorxx\"></span>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <form action=\"../../page2\" method=\"post\" class=\"sign-up-form\">\r\n");
      out.write("            <h2 class=\"title\">SIGN UP</h2>\r\n");
      out.write("            <p style=\"color:red\">");
      out.print( msg );
      out.write("</p>\r\n");
      out.write("            <div class=\"input-field\">\r\n");
      out.write("              <i class=\"fas fa-user\"></i>\r\n");
      out.write("              <input type=\"text\" placeholder=\"User ID\" name=\"userid\" id=\"userid\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-field\">\r\n");
      out.write("              <i class=\"fas fa-envelope\"></i>\r\n");
      out.write("              <input type=\"password\" placeholder=\"Password (6 Digits)\" name=\"password\" id=\"password\" maxlength=\"6\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"input-field\">\r\n");
      out.write("              <i class=\"fas fa-lock\"></i>\r\n");
      out.write("              <input type=\"text\" placeholder=\"VerifyWord (16 Digits)\" name=\"verifyWord\" id=\"verifyWord\" maxlength=\"16\"/>\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"submit\" class=\"btn\" value=\"Next ➜\" id=\"btn-submit\" disabled/>\r\n");
      out.write("          </form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"panels-container\">\r\n");
      out.write("        <div class=\"panel left-panel\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"panel right-panel\">\r\n");
      out.write("          <div class=\"content\">\r\n");
      out.write("            <h3>One of us ?</h3>\r\n");
      out.write("            <p>\r\n");
      out.write("              Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum\r\n");
      out.write("              laboriosam ad deleniti.\r\n");
      out.write("            </p>\r\n");
      out.write("            <button class=\"btn transparent\" id=\"sign-in-btn\">\r\n");
      out.write("              <a style=\"text-decoration: none;color:white;\" href=\"../../MeyBank_SignIn/page/signin.jsp\">Sign in</a>\r\n");
      out.write("            </button>\r\n");
      out.write("          </div>\r\n");
      out.write("          <img src=\"../../image/undraw_Online_payments_re_y8f2-removebg-preview.png\" class=\"image\" alt=\"\" />\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("    <script src=\"../script/page2.js\"></script>\r\n");
      out.write("  </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
