/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-21 02:59:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.MeyBank_005fSignIn.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class forgetpassword_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("    <head>\r\n");
      out.write("        <meta charset=\"UTF-8\">\r\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("\r\n");
      out.write("        <link rel=\"stylesheet\" href=\"../css/forget.css\">\r\n");
      out.write("        <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>\r\n");
      out.write("\r\n");
      out.write("        <title>Login form responsive</title>  \r\n");
      out.write("    </head>\r\n");
      out.write("    <body>\r\n");
      out.write("    \r\n");
      out.write("    ");

		String msg = (String)session.getAttribute("errorforgetpassword");
		if(msg == null){
			msg = "";
		}
	
      out.write("\r\n");
      out.write("    \r\n");
      out.write("        <div class=\"l-form\">\r\n");
      out.write("            <div class=\"shape1\"></div>\r\n");
      out.write("            <div class=\"shape2\"></div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form\">\r\n");
      out.write("                <img src=\"../../image/authentication.svg\" alt=\"\" class=\"form__img\">\r\n");
      out.write("\r\n");
      out.write("                <form action=\"../../forgetpassword\" method=\"post\" class=\"form__content\">\r\n");
      out.write("                    <h1 class=\"form__title\">Forgot Password</h1>\r\n");
      out.write("                    <p style=\"color:red;text-align:center;font-family: 'Raleway', sans-serif;font-size:0.8rem;\">");
      out.print( msg );
      out.write("</p>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form__div form__div-one\">\r\n");
      out.write("                        <div class=\"form__icon\">\r\n");
      out.write("                            <i class='bx bx-user-circle'></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form__div-input\">\r\n");
      out.write("                            <label for=\"\" class=\"form__label\">Card Number</label>\r\n");
      out.write("                            <input type=\"text\" class=\"form__input\" name=\"card\" maxlength=\"16\" id=\"card\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"form__div\">\r\n");
      out.write("                        <div class=\"form__icon\">\r\n");
      out.write("                            <i class='bx bx-lock' ></i>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"form__div-input\">\r\n");
      out.write("                            <label for=\"\" class=\"form__label\">Pin Number</label>\r\n");
      out.write("                            <input type=\"password\" class=\"form__input\" name=\"pin\" maxlength=\"3\" id=\"pin\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <br/>\r\n");
      out.write("                    <input type=\"submit\" class=\"form__button\" value=\"Submit\" id=\"sure\" disabled>\r\n");
      out.write("                    <input type=\"button\" id=\"banktohome\" class=\"form__button\" value=\"Bank To Login\">\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.6.3.min.js\"></script>\r\n");
      out.write("        <script src=\"../script/forget.js\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("    	$(function(){\r\n");
      out.write("    		$(\"#banktohome\").click(function(){\r\n");
      out.write("    			window.location.href=\"signin.jsp\";\r\n");
      out.write("    		})\r\n");
      out.write("    		\r\n");
      out.write("    		var cardnumber = false;\r\n");
      out.write("    		var pinnumber = false;\r\n");
      out.write("    		\r\n");
      out.write("    		\r\n");
      out.write("    		$(\"#card\").keyup(function(){\r\n");
      out.write("    			if($(this).val() != \"\" && $(this).val().length == 16){\r\n");
      out.write("    				cardnumber = true;\r\n");
      out.write("    			}else{\r\n");
      out.write("    				cardnumber = false;\r\n");
      out.write("    			}\r\n");
      out.write("    			CheckOPen(cardnumber,pinnumber);\r\n");
      out.write("    		})\r\n");
      out.write("    		\r\n");
      out.write("    		$(\"#pin\").keyup(function(){\r\n");
      out.write("    			if($(this).val() != \"\" && $(this).val().length == 3){\r\n");
      out.write("    				pinnumber = true;\r\n");
      out.write("    			}else{\r\n");
      out.write("    				pinnumber = false;\r\n");
      out.write("    			}\r\n");
      out.write("    			CheckOPen(cardnumber,pinnumber);\r\n");
      out.write("    		})\r\n");
      out.write("    		\r\n");
      out.write("    		function CheckOPen(cardnumber,pinnumber){\r\n");
      out.write("    			if(cardnumber == true && pinnumber == true){\r\n");
      out.write("    				$(\"#sure\").prop(\"disabled\",false);\r\n");
      out.write("    			}else{\r\n");
      out.write("    				$(\"#sure\").prop(\"disabled\",true);\r\n");
      out.write("    			}\r\n");
      out.write("    		}\r\n");
      out.write("    		\r\n");
      out.write("    	})\r\n");
      out.write("    </script>\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
