/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-02-28 06:50:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Models.*;
import java.util.*;
import Models.*;

public final class EditAccount_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Admin/page/../../Layout/Admin.jsp", Long.valueOf(1677319155573L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("Models");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    	Admin admin = (Admin)session.getAttribute("Admin");
		if(admin == null){
			response.sendRedirect("../../Admin/page/Login.jsp");
			return;
		}

      out.write('\r');
      out.write('\n');
 
	Admin ad = (Admin)session.getAttribute("Admin");
Account account = (Account)session.getAttribute("editaccountadmin");

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog==\"\r\n");
      out.write("	crossorigin=\"anonymous\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/editacocunt.css\" />\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");

		String msg = (String)session.getAttribute("editaccountwrong");
		if(msg == null){
			msg = "";
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<form action=\"../../EditAccount\" method=\"post\">\r\n");
      out.write("		<div id=\"wrapper\">\r\n");
      out.write("			<div id=\"left\">\r\n");
      out.write("				<div id=\"signin\">\r\n");
      out.write("					<div class=\"logo\">\r\n");
      out.write("						<h1>\r\n");
      out.write("							MeyBank <span style=\"color: red;\">Online</span>\r\n");
      out.write("						</h1>\r\n");
      out.write("					</div>\r\n");
      out.write("					<p style=\"color:red\">");
      out.print(msg );
      out.write("</p>\r\n");
      out.write("					<div class=\"form\">\r\n");
      out.write("						<div>\r\n");
      out.write("							<label>User Name</label> <input type=\"text\" id=\"MyGmail\"\r\n");
      out.write("								class=\"text-input\" name=\"Username\" value=\"");
      out.print( account.getUsername() );
      out.write("\" required />\r\n");
      out.write("						</div>\r\n");
      out.write("						<div>\r\n");
      out.write("							<label>VerifyWord</label> <input type=\"text\" id=\"MyGmail\"\r\n");
      out.write("								class=\"text-input\" name=\"VerifyWord\" value=\"");
      out.print( account.getVerifyWord() );
      out.write("\" maxlength=\"16\" required />\r\n");
      out.write("						</div>\r\n");
      out.write("						<button type=\"submit\" class=\"primary-btn\" id=\"mysubmit\">Submit</button>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"or\">\r\n");
      out.write("						<hr class=\"bar\" />\r\n");
      out.write("						<span>OR</span>\r\n");
      out.write("						<hr class=\"bar\" />\r\n");
      out.write("					</div>\r\n");
      out.write("					<a href=\"admin_home.jsp\" class=\"secondary-btn\">Back To Home</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<footer id=\"main-footer\">\r\n");
      out.write("					<p>Copyright 2022/7/14, Create by Hoo</p>\r\n");
      out.write("					<div>\r\n");
      out.write("						<a href=\"https://www.facebook.com/profile.php?id=100075495878672\">Terms\r\n");
      out.write("							of use</a> | <a href=\"#\">Privacy Policy</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</footer>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"right\">\r\n");
      out.write("				<div id=\"showcase\">\r\n");
      out.write("					<div class=\"showcase-content\"></div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script\r\n");
      out.write("	src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
