/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.0.27
 * Generated at: 2023-03-01 06:15:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Admin.page;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import Models.*;
import java.util.*;
import Models.*;

public final class viewtr_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/Admin/page/../../Layout/Admin.jsp", Long.valueOf(1677319155573L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_packages.add("Models");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP 只允许 GET、POST 或 HEAD。Jasper 还允许 OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    ");

    	Admin admin = (Admin)session.getAttribute("Admin");
		if(admin == null){
			response.sendRedirect("../../Admin/page/Login.jsp");
			return;
		}

      out.write("\r\n");
      out.write("	\r\n");

Account Otheracc = (Account)session.getAttribute("OtherAccount");
BankAccount Otherbank = (BankAccount)session.getAttribute("OtherBankAccount");
User Otheruser = (User)session.getAttribute("OtherUser");
Transaction Othertr = (Transaction)session.getAttribute("tr1");
String amount = String.format("%.2f", Othertr.getAmount()).toString();
String sms = String.format("%.2f", Othertr.getSMSNotification()).toString(); 

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css\"\r\n");
      out.write("	integrity=\"sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==\"\r\n");
      out.write("	crossorigin=\"anonymous\" referrerpolicy=\"no-referrer\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/viewtr.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"main\">\r\n");
      out.write("		\r\n");
      out.write("		<h1 style=\"display: none;\" id=\"mcid\">@ViewBag.trID</h1>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"my_box\">\r\n");
      out.write("		<img src=\"../../image/meybank-logo.png\" alt=\"Logo\"\r\n");
      out.write("			class=\"brand-image img-circle elevation-3\"> <span\r\n");
      out.write("			class=\"brand-text font-weight-light\"\r\n");
      out.write("			style=\"font-family: 'Times New Roman', Times, serif; color: white;\">MeyBank\r\n");
      out.write("			<span style=\"color: red;\">Online</span>\r\n");
      out.write("		</span>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"my_box2\">\r\n");
      out.write("		<hr />\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("\r\n");
      out.write("		<h2>MEYBANK ONLINE HISTORY</h2>\r\n");
      out.write("		<div class=\"flex\">\r\n");
      out.write("			<div class=\"f1\">\r\n");
      out.write("				<p>Reference Number :</p>\r\n");
      out.write("				<p>Transaction Status :</p>\r\n");
      out.write("				<p>Transaction Date/Time :</p>\r\n");
      out.write("				<p>From Account :</p>\r\n");
      out.write("				<p>Amount :</p>\r\n");
      out.write("				<br/>\r\n");
      out.write("				<p>Transfer Type :</p>\r\n");
      out.write("				<p>Beneficiary Bank :</p>\r\n");
      out.write("				<p>Beneficiary Account :</p>\r\n");
      out.write("				<p>Beneficiary Account Type :</p>\r\n");
      out.write("				<p>Beneficiary Name :</p>\r\n");
      out.write("				<p>Recipient Reference :</p>\r\n");
      out.write("				<p>Other Payment Detail :</p>\r\n");
      out.write("				<p>DuitNow Transfer Service Charge :</p>\r\n");
      out.write("				<p>Total Charges :</p>\r\n");
      out.write("				<br/>\r\n");
      out.write("				<p>SMS Notification Charge :</p>\r\n");
      out.write("				<p>Total Charges :</p>\r\n");
      out.write("				<br/>\r\n");
      out.write("				<p>Beneficiary's mobile phone number :</p>\r\n");
      out.write("				<p>Beneficiary's email :</p>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"f2\" id=\"TrDetail\">\r\n");
      out.write("				<p>223417</p>\r\n");
      out.write("				<p>Successful</p>\r\n");
      out.write("				<p>");
      out.print( Othertr.getDate() );
      out.write("</p>\r\n");
      out.write("				<p>");
      out.print( Othertr.getDebit() );
      out.write("</p>\r\n");
      out.write("				<p>RM ");
      out.print( amount );
      out.write("</p>\r\n");
      out.write("				<br/>\r\n");
      out.write("				<p>");
      out.print( Othertr.getTransactionType() );
      out.write("</p>\r\n");
      out.write("				");
 String acctype = "null";
				if(Otheracc != null)
					acctype = Otheracc.getBankType();
				
      out.write("\r\n");
      out.write("				<p>");
      out.print( acctype );
      out.write("</p>\r\n");
      out.write("				<p>");
      out.print( Othertr.getCredit() );
      out.write("</p>\r\n");
      out.write("				");
 String banktype = "null";
				if(Otherbank != null)
					banktype = Otherbank.getAccountType();
				
      out.write("\r\n");
      out.write("				<p>");
      out.print( banktype );
      out.write("</p>\r\n");
      out.write("				");
 String fullname = "null";
				if(Otheruser != null)
					fullname = Otheruser.getFullName();
				
      out.write("\r\n");
      out.write("				<p>");
      out.print( fullname );
      out.write("</p>\r\n");
      out.write("				<p>");
      out.print( Othertr.getDescription() );
      out.write("</p>\r\n");
      out.write("				<p>");
      out.print( Othertr.getOtherDescription() );
      out.write("</p>\r\n");
      out.write("				<p>RM 0.00</p>\r\n");
      out.write("				<p>RM 0.00</p>\r\n");
      out.write("				<br/>\r\n");
      out.write("				<p>RM ");
      out.print( sms );
      out.write("</p>\r\n");
      out.write("				<p>RM ");
      out.print( sms );
      out.write("</p>\r\n");
      out.write("				<br/>\r\n");
      out.write("				<p>");
      out.print( Othertr.getPhoneNumber() );
      out.write("</p>\r\n");
      out.write("				<p>");
      out.print( Othertr.getEmail() );
      out.write("</p>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("		\r\n");
      out.write("	\r\n");
      out.write("	</div>\r\n");
      out.write("	<div class=\"btn\">\r\n");
      out.write("		<a class=\"b1\" href=\"history.jsp\" id=\"b1\">Back</a>\r\n");
      out.write("		<button class=\"b1 b2\" onclick=\"loadPrint()\" id=\"b2\">Print</button>\r\n");
      out.write("		<button class=\"b1 b2\" onclick=\"pdfDo()\" id=\"b3\">Download PDF</button>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script\r\n");
      out.write("		src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("		 <script src=\"https://cdn.bootcss.com/html2canvas/0.5.0-beta4/html2canvas.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.bootcss.com/jspdf/1.3.4/jspdf.debug.js\"></script>\r\n");
      out.write("	<script>\r\n");
      out.write("\r\n");
      out.write("		function loadPrint() {\r\n");
      out.write("			b1.style.display = \"none\";\r\n");
      out.write("			b2.style.display = \"none\";\r\n");
      out.write("			b3.style.display = \"none\";\r\n");
      out.write("			window.print();\r\n");
      out.write("			b1.style.display = \"block\";\r\n");
      out.write("			b2.style.display = \"block\";\r\n");
      out.write("			b3.style.display = \"block\";\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("		 function pdfDo() {\r\n");
      out.write("	          var isDo = confirm(\"确定导出pdf页面\");\r\n");
      out.write("	          if (!isDo) { return; }\r\n");
      out.write("	          var target = document.getElementsByClassName(\"main\")[0];\r\n");
      out.write("	          \r\n");
      out.write("	          html2canvas(target, {\r\n");
      out.write("	              onrendered: function (canvas) {\r\n");
      out.write("	                  var contentWidth = canvas.width;\r\n");
      out.write("	                  var contentHeight = canvas.height;\r\n");
      out.write("\r\n");
      out.write("	                  //一页pdf显示html页面生成的canvas高度;\r\n");
      out.write("// 	                  var pageHeight = contentWidth / 592.28 * 841.89;\r\n");
      out.write("	                  var pageHeight = contentWidth / 592.28 * 90001.89;\r\n");
      out.write("	                  //未生成pdf的html页面高度\r\n");
      out.write("	                  var leftHeight = contentHeight;\r\n");
      out.write("	                  //页面偏移\r\n");
      out.write("	                  var position = 0;\r\n");
      out.write("	                  //a4纸的尺寸[595.28,841.89]，html页面生成的canvas在pdf中图片的宽高\r\n");
      out.write("	                  var imgWidth = 595.28;\r\n");
      out.write("	                  var imgHeight = 592.28 / contentWidth * contentHeight;\r\n");
      out.write("	  \r\n");
      out.write("	                  var pageData = canvas.toDataURL('image/jpeg', 1.0);\r\n");
      out.write("	  \r\n");
      out.write("	                  var pdf = new jsPDF('', 'pt', 'a4');\r\n");
      out.write("	  \r\n");
      out.write("	                  //有两个高度需要区分，一个是html页面的实际高度，和生成pdf的页面高度(841.89)\r\n");
      out.write("	                  //当内容未超过pdf一页显示的范围，无需分页\r\n");
      out.write("	                  if (leftHeight < pageHeight) {\r\n");
      out.write("	                      pdf.addImage(pageData, 'JPEG', 0, 0, imgWidth, imgHeight);\r\n");
      out.write("	                  } else {\r\n");
      out.write("	                      while (leftHeight > 0) {\r\n");
      out.write("	                          pdf.addImage(pageData, 'JPEG', 0, position, imgWidth, imgHeight)\r\n");
      out.write("	                          leftHeight -= pageHeight;\r\n");
      out.write("	                          position -= 841.89;\r\n");
      out.write("	                          //避免添加空白页\r\n");
      out.write("	                          if (leftHeight > 0) {\r\n");
      out.write("	                              pdf.addPage();\r\n");
      out.write("	                          }\r\n");
      out.write("	                      }\r\n");
      out.write("	                  }\r\n");
      out.write("	                  pdf.save(\"pdf_file_name.pdf\");\r\n");
      out.write("	              }\r\n");
      out.write("	          })\r\n");
      out.write("	      }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
